# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['bill_extractor.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'bollette',
        'bollette.models',
        'bollette.extractors',
        'bollette.exporters',
        'bollette.electricity.builder',
        'bollette.electricity.constants',
        'bollette.electricity.extractors',
        'bollette.electricity.quality',
        'bollette.electricity.templates',
        'bollette.electricity.templates.base',
        'bollette.electricity.templates.octopus',
        'bollette.electricity.templates.acea',
        'bollette.electricity.templates.a2a',
        'bollette.electricity.templates.enel',
        'bollette.electricity.templates.iren',
        'bollette.electricity.templates.sen',
        'bollette.electricity.templates.edison',
        'bollette.gas.builder',
        'bollette.gas.extractors',
        'bollette.gas.templates',
        'bollette.gas.templates.base',
        'bollette.gas.templates.dolomiti',
        'dateutil',
        'dateutil.parser',
        'dateutil.tz',
        'dateutil.relativedelta',
        'pypdf',
        'pypdf._reader',
        'pypdf._page',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.styles.numbers',
        'openpyxl.utils',
        'openpyxl.utils.dataframe',
        'pandas',
        'pandas.io.formats.excel',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='bollette-cli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,           # tool da riga di comando: mostra terminale
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
