# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['bill_extractor.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'bollette',
        'bollette.models',
        'bollette.constants',
        'bollette.text_utils',
        'bollette.extractors',
        'bollette.builder',
        'bollette.exporters',
        'bollette.templates',
        'bollette.templates.base',
        'bollette.templates.octopus',
        'bollette.templates.acea',
        'dateutil',
        'dateutil.parser',
        'dateutil.tz',
        'dateutil.relativedelta',
        'pypdf',
        'pypdf._reader',
        'pypdf._page',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.styles.numbers',
        'openpyxl.utils',
        'openpyxl.utils.dataframe',
        'pandas',
        'pandas.io.formats.excel',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='bollette-cli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,           # tool da riga di comando: mostra terminale
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
